version: 2
updates:

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: "chore"
    groups:
      dev-dependencies:
        dependency-type: development
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"
      opentelemetry:
        patterns:
          - "@opentelemetry/*"
      fastify:
        patterns:
          - "fastify"
          - "@fastify/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
    commit-message:
      prefix: "chore(ci)"
